{
 "title": "SRE Demo Dashboard Copy",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "[Api] HTTP 500 Error Rate (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_total{path=\"/error\",status=\"500\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "[API] Total HTTP 500 Errors",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "http_requests_total{path=\"/health\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Health Check Requests Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_requests_total{path=\"/health\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}