apiVersion: v1
kind: Service
metadata:
  name: sre-demo-service
  namespace: sre-demo
spec:
  selector:
    app: sre-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP